config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'}
  resources :users
  resources :products
  resources :categories
  get 'pages/home'

  get 'pages/about'
  root to: 'pages#home', as: :root

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :child, class_name: 'Category', foreign_key: :parent_id
  belongs_to :parent, class_name: 'Category', foreign_key: :parent_id

  has_many :products, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :timeoutable, :lockable
  #has_many :products, through: :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :remember_me, :password_confirmation) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :address, :address2, :city, :state, :country, :zipcode, :phone, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :icon, :tag, :parent_id, :published, :slug)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @products = Product.all.order('id desc')
  end

  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :content, :price, :buyer, :data_file, :manufacturer, :category_id, :published, :tags, :language, :slug)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :address, :address2, :city, :state, :country, :zipcode, :phone, :language)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'uri'

  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identicon&s=350"
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :category_title %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon, id: :category_icon %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.number_field :tag, id: :category_tag %>
  </div>

  <div class="field">
    <%= form.label :parent_id %>
    <%= form.number_field :parent_id, id: :category_parent_id %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published, id: :category_published %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug, id: :category_slug %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Icon</th>
      <th>Tag</th>
      <th>Parent</th>
      <th>Published</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.icon %></td>
        <td><%= category.tag %></td>
        <td><%= category.parent_id %></td>
        <td><%= category.published %></td>
        <td><%= category.slug %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @category.icon %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @category.tag %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @category.parent_id %>
</p>

<p>
  <strong>Published:</strong>
  <%= @category.published %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @category.slug %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatalogShop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

  </head>

  <body>
      <%= render partial: 'shared/header' %>
      <main>
        <%= yield %>
      </main>
      <%= render partial: 'shared/footer' %>
  </body>
  <script>
    $(document).ready(function () {
      $(".button-collapse").sideNav();
      $(".dropdown-button").dropdown();

    });

  </script>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div class="row row-space-home-page"></div>

<div class="container" id="customize-home-container">
  <div class="row">
<div class="col s12 m12 l3 left-menu-tab">
<%= render partial: 'shared/category' %>
</div>
<div class="col s12 m12 l9">
  <% if @products.present? && @products.count > 0 %>
  <div class="row row-latest-home-items">
  <%= render partial: 'shared/products' %>
  </div>
  <% end %>

</div>

</div>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :product_content %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :buyer %>
    <%= form.number_field :buyer, id: :product_buyer %>
  </div>

  <div class="field">
    <%= form.label :data_file %>
    <%= form.text_field :data_file, id: :product_data_file %>
  </div>

  <div class="field">
    <%= form.label :manufacturer %>
    <%= form.text_field :manufacturer, id: :product_manufacturer %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id, id: :product_category_id %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published, id: :product_published %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags, id: :product_tags %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language, id: :product_language %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug, id: :product_slug %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">
  <div class="row"></div>
  <div class="row"></div>

  <div class="row">
    <%= render  partial: 'shared/products' %>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @product.content %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Buyer:</strong>
  <%= @product.buyer %>
</p>

<p>
  <strong>Data file:</strong>
  <%= @product.data_file %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @product.manufacturer %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Published:</strong>
  <%= @product.published %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @product.tags %>
</p>

<p>
  <strong>Language:</strong>
  <%= @product.language %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @product.slug %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_category.html.erb
<div id="leftpanel">
  <div class="card">
    <ul>
      <% Category.all.includes(:parent, :child).sort_by {|e| e[:tag]}.each do |category| %>
        <% if category.parent.blank? %>
          <%= render '/shared/sub_category', category: category %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="page-footer blue-grey darken-3">
  <div class="container" id="customize-home-container">
    <div class="row">
      <div class="col s12 m6 l6 center">
        <h5 class="white-text">Connect us</h5>
        <ul>
          <li>
            <%= link_to image_tag('youtube48.png', :alt => 'YouTube'), root_path, class: 'image-social-footer', target: :blank %>
            <%= link_to image_tag('facebook48.png', :alt => 'Facebook'), root_path, class: 'image-social-footer', target: :blank %>
          </li>
        </ul>
      </div>
      <div class="col s12 m6 l4 offset-l2 center">
        <h5 class="white-text">Sports Car Shop</h5>
        <ul>
          <li><%= link_to 'About Us', root_path , :class => 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'Help', root_path , class: 'grey-text text-lighten-3' %></li>
          <li><%= link_to 'Terms of Use', root_path , :class => 'grey-text text-lighten-3' %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2017 Copyright Rossnaive
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <ul id="dropdown1" class="dropdown-content">
    <li class="item_category_mobile">
      <%= link_to edit_user_registration_path do %>
          <i class="material-icons md-24 icon-cate-in-mobile">settings</i>Account Settings
      <% end %>
    </li>

    <li class="item_category_mobile">
      <%= link_to root_path do %>
          <i class="material-icons md-24 icon-cate-in-mobile">history</i>History Orders
      <% end %>
    </li>

    <li class="divider"></li>

    <li class="item_category_mobile">
      <%= link_to destroy_user_session_path, method: :delete, title: 'Logout' do %>
          <i class="material-icons md-24 icon-cate-in-mobile">settings_power</i>Logout
      <% end %>
    </li>
  </ul>

  <nav class="blue-grey darken-3 z-depth-2" id="nav-header-shop">
    <div class="container" id="customize-home-container">
      <div class="nav-wrapper">
        <%= link_to image_tag('logo.png'), root_path, class: 'brand-logo' %>

        <a href="#" data-activates="mobile-demo" class="button-collapse">
          <i class="material-icons">menu</i>
        </a>

        <ul class="right hide-on-med-and-down">
          <li class="li-list-item-top-menu">
            <ul class="ul-list-item-header">
              <a class="link-to-item-header" href="#">
                <li class="li-list-item-header">
                  <i class="material-icons md-24 icon-in-top-menu">time_to_leave</i>
                </li>
                <li class="li-list-item-header">Cars</li>
              </a>
            </ul>
          </li>

          <!--<li class="li-list-item-top-menu">
            <ul class="ul-list-item-header">
              <a class="link-to-item-header" href="#">
                <li class="li-list-item-header">
                  <i class="material-icons md-24 icon-in-top-menu">settings</i>
                </li>
                <li class="li-list-item-header">Machines</li>
              </a>
            </ul>
          </li> -->

          



          <% if !user_signed_in? %>
              <li class="li-list-item-top-menu">
                <ul class="ul-list-item-header">
                  <%= link_to new_user_registration_path, class: 'link-to-item-header' do %>
                      <li class="li-list-item-header">
                        <i class="material-icons md-24 icons-task-header-menu">person_add</i>
                      </li>
                      <li class="li-list-item-header">
                        Sign Up
                      </li>
                  <% end %>
                </ul>
              </li>

              <li class="li-list-item-top-menu">
                <ul class="ul-list-item-header">
                  <%= link_to new_user_session_path, class: 'link-to-item-header' do %>
                      <li class="li-list-item-header">
                        <i class="material-icons md-24 icons-task-header-menu">lock</i>
                      </li>
                      <li class="li-list-item-header">
                        Login
                      </li>
                  <% end %>
                </ul>
              </li>
          <% else %>
              <li>
                <a class="dropdown-button valign-wrapper" href="#" data-activates="dropdown1">
                  <%= image_tag avatar_url(current_user), class: 'circle responsive-img avatar-small' %>&nbsp;
                  <%= current_user.name %>
                  <i class="material-icons md-36">arrow_drop_down</i>
                </a>
              </li>

              <li>
                <%= link_to destroy_user_session_path, method: :delete, title: 'Logout' do %>
                    <i class="material-icons md-36" id="logout-button">settings_power</i>
                <% end %>
              </li>

          <% end %>

        </ul>

        <ul class="side-nav" id="mobile-demo">
          <div class="title-sign-up-page center">
            <% if !user_signed_in? %>
                <span> Sport Car Shop</span>
            <% else %>
                <li class="item_avatar_mobile" id="image-avatar-in-side-nav">
                  <%= image_tag avatar_url(current_user), class: 'circle responsive-img avatar-small', id: 'image-avatar-in-side-bar' %>
                </li>
                <li class="item_avatar_mobile">
                  <%= current_user.name %>
                </li>
                <li class="item_avatar_mobile">
                  <%= current_user.email %>
                </li>
            <% end %>
          </div>

          <% if !user_signed_in? %>
              <li class="item_category_mobile">
                <%= link_to new_user_registration_path do %>
                    <i class="material-icons md-24 icon-cate-in-mobile">person_add</i>Sign Up
                <% end %>
              </li>
              <li class="item_category_mobile">
                <%= link_to new_user_session_path do %>
                    <i class="material-icons md-24 icon-cate-in-mobile">lock</i>Login
                <% end %>
              </li>
          <% else %>
              <li class="item_category_mobile">
                <%= link_to edit_user_registration_path do %>
                    <i class="material-icons md-24 icon-cate-in-mobile">settings</i>Account Settings
                <% end %>
              </li>
              <li class="item_category_mobile">
                <%= link_to root_path do %>
                    <i class="material-icons md-24 icon-cate-in-mobile">history</i>History Order
                <% end %>
              </li>
              <li class="divider"></li>
              <li class="item_category_mobile">
                <%= link_to destroy_user_session_path, method: :delete, title: 'Logout' do %>
                    <i class="material-icons md-24 icon-cate-in-mobile">settings_power</i>Logout
                <% end %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_products.html.erb
<% @products.each do |product| %>
    <div class="col s12 m6 l4">
      <%= link_to product do %>
          <div class="card z-depth-2">
            <div class="card-image">
              <%= image_tag 'car.jpg' %>
            </div>
            <div class="card-content">
              <span class="card-title"><%= product.name %></span>
              <%= product.content.html_safe %>
            </div>
      <% end %>
      <div class="card-action">
        <div class="row">
          <div class="col s6 l4">
            <%= product.price %>
          </div>
          <div class="col s6 l8">
            <a href="#" class="waves-effect waves-light btn right">Add to cart</a>
          </div>
        </div>
      </div>
      </div>
    </div>
<% end %>

app/views/shared/_sub_category.html.erb
<% if category.child.present? %>
    <% if category.published %>
        <li class="item_category_parent">
          <i class="material-icons md-36 icon-cate"><%= category.icon %></i>&nbsp; &nbsp;<%= category.title %>
        </li>
    <% end %>

    <% category.child.sort_by {|e| e[:tag]}.each do |child| %>
        <% if child.published %>
            <%= render '/shared/sub_category', category: child %>
        <% end %>
    <% end %>
<% else %>
    <% if category.published %>
        <li class="item_category">
          <%= link_to '<i class="material-icons md-36 icon-cate">'.html_safe + category.icon + '</i>&nbsp; &nbsp;'.html_safe + category.title, root_path %>
        </li>
    <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :user_address %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2, id: :user_address2 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :user_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :user_state %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :user_country %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode, id: :user_zipcode %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :user_phone %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language, id: :user_language %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Zipcode</th>
      <th>Phone</th>
      <th>Language</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.address %></td>
        <td><%= user.address2 %></td>
        <td><%= user.city %></td>
        <td><%= user.state %></td>
        <td><%= user.country %></td>
        <td><%= user.zipcode %></td>
        <td><%= user.phone %></td>
        <td><%= user.language %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @user.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @user.country %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @user.zipcode %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Language:</strong>
  <%= @user.language %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>